#!/usr/bin/env bash
set -e

# Detect the operating system
if [[ "$(uname)" == "Darwin" ]]; then
	echo "Detected macOS. Using Homebrew."
	brew install cmake gettext lua luarocks
elif [ -f /etc/os-release ]; then
	. /etc/os-release
	if [[ "$ID" == "ubuntu" ]]; then
		echo "Detected Ubuntu. Using apt-get."
		sudo apt-get update
		sudo apt-get install -y cmake gettext liblua luarocks
	elif [[ "$ID" == "rocky" || "$ID_LIKE" == *"rhel"* ]]; then
		echo "Detected Rocky Linux or a RHEL-based system. Using dnf."
		sudo dnf install -y cmake gettext lua-devel luarocks
	else
		echo "Unsupported Linux distribution: $ID"
		exit 1
	fi
else
	echo "Unsupported operating system."
	exit 1
fi

# Clone the Neovim repo
git clone --branch v0.11.0 git@github.com:neovim/neovim.git $HOME/personal/neovim

# Build and install neovim
cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
