#!/usr/bin/env bash
set -e

# Detect the operating system
if [[ "$(uname)" == "Darwin" ]]; then
	echo "Detected macOS. Using Homebrew."
	brew install automake pkg-config libevent utf8proc
elif [ -f /etc/os-release ]; then
	. /etc/os-release
	if [[ "$ID" == "ubuntu" ]]; then
		echo "Detected Ubuntu. Using apt-get."
		sudo apt-get update
		sudo apt-get install -y automake pkg-config libevent-dev libutf8proc-de
	elif [[ "$ID" == "rocky" || "$ID_LIKE" == *"rhel"* ]]; then
		echo "Detected Rocky Linux or a RHEL-based system. Using dnf."
		sudo dnf install -y automake pkgconfig libevent-devel utf8proc-devel
	else
		echo "Unsupported Linux distribution: $ID"
		exit 1
	fi
else
	echo "Unsupported operating system."
	exit 1
fi

# Clone the tmux repo
git clone https://github.com/tmux/tmux.git $HOME/personal/tmux

# Build tmux
cd $HOME/personal/tmux
sh autogen.sh
./configure --enable-utf8proc && make

# Copy the tmux binary to a directory in the PATH
sudo cp $HOME/personal/tmux/tmux /usr/local/bin/tmux
